### ISSUE TITLE
无法解析数组参数

### ISSUE THREAD

**Issue by crazystory** [go-macaron/binding#16]
```
type ConsoleForm struct {
	Operation string   `form:"operation"`
	Command   string   `form:"command"`
	Args      []string `form:"args"`
}
```

发送参数operation=test&command=run&args[]=1&args[]=2

args无法映射到struct中

**Comment by Unknwon** [comment]
你这用法不对吧，`operation=test&command=run&args=1&args=2` 试试？

**Comment by crazystory** [comment]
写法没问题哦..http的数组是这样传的 PHP和python都能正确接收
追踪代码的时候*http.Request里也能找到1和2这两个值,但是映射不到form里

**Comment by Unknwon** [comment]
>追踪代码的时候*http.Request里也能找到1和2这两个值

代码举证？。。。

**Comment by crazystory** [comment]
`operation=test&command=run&args=1&args=2`
这段试过了,也无法映射到strcut里
但是如果改为
```
type ConsoleForm struct {
	Operation string   `form:"operation"`
	Command   string   `form:"command"`
	Args      string `form:"args"`
}```
可以获取到2这个值

在php中`operation=test&command=run&args[]=1&args[]=2`
GET请求中能得到
```
$_GET['args']的值为 array(1, 2)
```

**Comment by Unknwon** [comment]
我问的是 Go 的代码举证。。

**Comment by spkinger** [comment]
`type ConsoleForm struct {
	Args      []string `form:"args[]"`
}`

我也遇到这个问题，我按如上方式绑定，
POST参数args[]
args[0]=1
args[1]=2

Args依然为空数组[]

**Comment by Unknwon** [comment]
不要使用PHP的方式

试试 command=run&args=1&args=2

**Comment by spkinger** [comment]
[https://github.com/gin-gonic/gin/issues/129#issuecomment-124260092](url)
这个是隔壁gin的绑定方式

如果像下面这样的参数
`<form action="/" method="POST">
    <input type="checkbox" name="args[]" value="1" />
    <input type="checkbox" name="args[]" value="2" />
</form>`
macaron应该怎样接收呢

**Comment by Unknwon** [comment]
我测了完全没问题啊，用的 https://github.com/gin-gonic/gin/issues/129#issuecomment-124260092 里 form 的例子：

```go
package main

import (
	"fmt"

	"github.com/go-macaron/binding"
	"gopkg.in/macaron.v1"
)

type ConsoleForm struct {
	Args []string `form:"colors[]"`
}

func main() {
	m := macaron.Classic()
	m.Use(macaron.Renderer())
	m.Post("/", binding.Bind(ConsoleForm{}), func(form ConsoleForm) {
		fmt.Println(form)
	})
	m.Run()
}
```
```
[Macaron] 2018-11-08 04:00:38: Started POST / for [::1]
{[red green blue]}
```

**Comment by helloteemo** [comment]
```go

type ConsoleForm struct {
	Operation string   `form:"operation"`
	Command   string   `form:"command"`
	Args      []string `form:"args[]"`
}

```

可以使用这样来获取`args[]`参数绑定,但是这样做就以为着`args`参数不能被绑定到
