### ISSUE TITLE
建议增加设置,可自定义 binding 标识

### ISSUE THREAD

**Issue by Zeno-Code** [go-macaron/binding#18]
binding.go
line 348
field.Tag.Get("mytag")

**Comment by Unknwon** [comment]
为什么？

**Comment by Zeno-Code** [comment]
结构体好多地方需要共用,例如和某些ORM结合使用
结构体 tag 格式可能发生冲突

**Comment by Unknwon** [comment]
... binding 这么个性的名字也会冲突？

**Comment by Zeno-Code** [comment]
可能是我表达失误
不是冲突,是达到简化 tag 目的

不好意思,关闭吧,我好像知道怎么弄了

**Comment by Unknwon** [comment]
..... 一脸懵逼 :flushed:
