### ISSUE TITLE
[Feature Request] Enable macaron binding Validation outside a request context.

### ISSUE THREAD

**Issue by toni-moreno** [go-macaron/binding#22]
I've working with macaron/binding to validate input data from a API REST . But also could import data in JSON format from a file  with lots of json formated objects of diferent type (https://github.com/toni-moreno/snmpcollector/blob/master/pkg/data/impexp/import.go#L91) . In this use case I would like also validate as input in the same way than if inserted via API REST and validated with macaron/binding.

Would be interesting if we can use the same binding.Validate method  decoupled of the http request.

**Comment by Unknwon** [comment]
Hi, you can now use `binding.RawValidate`, see details in https://github.com/go-macaron/binding/commit/894aec4d902fbb4001d668f4ea5b74e8a1f8d56c.

**Comment by toni-moreno** [comment]
Hi @Unknwon .

I will do some test next days and I will report you about.

Thank you very much

**Comment by toni-moreno** [comment]
Hi @Unknwon  I've tested the new Rawvalidate and It seems to work ok. 

Thank you very much for this great work!
